version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: Lilit
      POSTGRES_PASSWORD: testtest
      POSTGRES_DB: apiBooks
    volumes:
      - ./db/:/var/lib/postgresql/data/